name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2.2']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Setup Database
      run: |
        bundle exec rake db:create
        bundle exec rake db:schema:load
    - name: Create data and run tests
      run: |
        bundle exec rails runner "user = User.create(username: 'testuser', password: 'testpassword', password_confirmation: 'testpassword'); if user.errors.any?; puts user.errors.full_messages; exit 1; end"
        bundle exec rails runner "stock = Stock.create(name: 'teststock', user_id: User.first.id, amount: 10, price: 10.0); if stock.errors.any?; puts stock.errors.full_messages; exit 1; end"
        bundle exec rails runner "sale = Sale.create(client_id: Client.first.id, stock_id: Stock.first.id, quantity: 1, total_price: 10.0, user_id: User.first.id); if sale.errors.any?; puts sale.errors.full_messages; exit 1; end"
        bundle exec rails runner "recipe = Recipe.create(sale_id: Sale.first.id, recipe_note: 'testnote'); if recipe.errors.any?; puts recipe.errors.full_messages; exit 1; end"
        bundle exec rails runner "beehive_group = BeehiveGroup.create(name: 'testgroup'); if beehive_group.errors.any?; puts beehive_group.errors.full_messages; exit 1; end"
        bundle exec rake
